apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
              claimName: database-persistent-volume-claim    
      containers:
      - name: postgres
        image: postgres
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 5432
        env: 
          - name: 'POSTGRES_PASSWORD'
            valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PG_PASSWORD
            #Replaced after creating a secret with: kubectl create secret generic pgpassword --from-literal PG_PASSWORD=password123
            # value: 'password123'
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data
            subPath: postgres
